---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: 10.245.68.164
    path: /opt
  persistentVolumeReclaimPolicy: Retain
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-volume
  storageClassName: ""
...
