---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
stringData:
  application.properties: |
    spring.datasource.url=${JDBC_URL:jdbc:postgresql://10.245.68.100:5432/db?user=app&password=pass}
    spring.jpa.open-in-view=false
    server.ssl.key-store=${KEY_STORE_PATH:classpath:keystore.jks}
    server.ssl.key-store-password=${KEY_STORE_PASS:passphrase}
    server.ssl.trust-store=${TRUST_STORE_PATH:classpath:truststore.jks}
    server.ssl.trust-store-password=${TRUST_STORE_PASS:passphrase}
    server.ssl.enabled-protocols=${SSL_ROTOCOLS:TLSv1.3}
    server.ssl.client-auth=${SSL_AUTH:want}
    # TODO: mount ./media as `volumes`
    app.media-path=${MEDIA_PATH:./media}
    spring.web.resources.static-locations=file:${app.media-path},classpath:/static/
data:
  truststore.jks: |
    MIIEhgIBAzCCBD8GCSqGSIb3DQEHAaCCBDAEggQsMIIEKDCCBCQGCSqGSIb3DQEHBqCCBBUwggQR
    AgEAMIIECgYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQUnqx2iJDGsxn7Kkux9m3aMP1b/bwC
    AwDDUICCA9AUKV1jVxxkqlSX68EetRxinC+CT7iMdHzYG7ymnqTPaS8BSv5/BNlj6eZgtgorzvwq
    WmQXKeQSCgzqMFlJhBrlW8CrfdAWR+aDrlOaRlxCQV8AJg1wJxYFF1Oxyf99r3M7WLSwdVJA1Ca6
    Y2vety9ludQkYrgxWffu96mu+Eqi/6JRwcWugGYrEH71wIorLSRLt0Q3FCeNpQt4Mrs/gutK//nV
    fjP0daA+G8h1EEXlC2e3H3XNYq4+IGwB2Kx2divxqoJNHudvBbssAG0e2Q6nZFYxJ2Kng9D583yH
    TwM4iRwHNbZBU2gayVogxIJqg2uFLJ73OqBmCP4SF7JDAMt5O6QNB9wBDXcA5EQ975LZxqeyUp7k
    Uk4kkxfHKHjz+1DUJOFcF+wC/Dc0HGfKCaEbkmlZDgKsdjie+Ygh7gNq1CWVKSjpFqnJ3W77UMHo
    DB/MnneqZlgXj+CUcYxhTHmw7zQ49XRDocPIJCYi5ZQi1CArsu+Uu8wXnT4kWkbHSL8RGVtG02+M
    Bxp8ou5tAxizE9xOE9hM1ScqCOrOTIll3zBDQXdFkwOUbU19gjbfo+hdQ7W7UIQi8EGEFh/kuKMW
    Vl4BzfRa0i2tl7ENSYtgLhMg6qb/y4aKsc++lOhOayqWsRMSKOCjmvMOVFP+YH5CfVfP8uqJaXWi
    8cQa/VycsZDyDAvdd5h3y6va6uo8UUTHrqOAAfO4HnTP+Fzv6Fc/6mC/SJbr8FGugqf7wYuk29T8
    ux2F+usKpL2DozvEmXbTEGsJgo6YuTW56NTPomttf+OqmUUF2eetXRatD7T+3Mtgqc18kuznpx2p
    nqdOc1ZU9h+ObEWdMnwWHHjQtSfuKN6qtRFtKruBbaDKvU6bD22Qms6wA5mWlZSnmVqjUqX0lWcS
    espPNU7HqMskUSju/heZ42oPhlOZZsCVeQSyenzdR0xjkBKHyR0jBieG5Nl1Lm2UtniNkRWmcQiD
    jOdq77dNvKT6tFfgkYweu+8q+tmXV74AXjbfhQMm9nEvhAcGmxczhwYRHjoHFpxdUtDD4nPK/rpx
    6FBZJZ+C0Kbv6/9KTQ8w5kpFlmn1Qbw3R5EauJCjJVLNGwUwc4v7N6+g/GKU8Fu7BNTcDbQtz7cp
    5UCyIz0byKhX4cpysWSzW6wsCWofr1bJzWvPmeyiQ43S+LXKUOYF64/g4s92QsSSe9dnR14rxpIU
    Mzg+uZjw6eCOC/fJmjejMi12fg+Z2lhZeR2VV9wxZWbwcdySzXwdpE6JUw89Vt/yYfzwcGwP3MOL
    75/9DIpwH8V+C/w9+nZPMD4wITAJBgUrDgMCGgUABBR9A4zTEyHg7gn9HqNW3Y0MsKIEMwQUye7A
    +ERgpdpcA8UR/ywA4HUtIQICAwGGoA==

  keystore.jks: |
    MIIJuwIBAzCCCXQGCSqGSIb3DQEHAaCCCWUEgglhMIIJXTCCBWkGCSqGSIb3DQEHAaCCBVoEggVW
    MIIFUjCCBU4GCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBQHZguOimq/bzEl
    FfPn57tg5pcHiwIDAMNQBIIEyEjXOWY4adH09Em6hppzGTbHw7Yji45Fl2hDjIEnViSuZrEjSyFe
    6nrNEXwi93RHU4DtZZlpd5ZEN0p5gNBvFFE8vSV0I4pS1BGOZlZvUuWjGydw/eOtentntsj2Vh+x
    3WruWbZiFxHgwYihOPhBTerIvGgYcpN2KNsUkB9VfC2io/RjsaWjIUdccs7kW+vKznuOY2pyHnKJ
    K001bhmSEDcR0lUUlRNKTzDns58zHNJ8M9y2kbx/7TITytxXykuDRxgUBSJ+JgkrfX2JHOfdQXgs
    SbZCSHs4qhbQ6pVuYWEWwjRgA1gcYfzf5oFtX8waFlu4VCuScR51p0vouTE+QRPhFgMxOBYmzJRO
    GnvH+HQoxoBTwbMFY+GgDQocY3+ThDtSRqv4DOP73gnQ5PS2xvuYAZaxs+Whp3wyderrbmfJxiqT
    B4oy+dteobHYwmr98DWV7s3KRKpnGoCOPYGlg2YgI/U15IvvyDY34pQVLn9vAUx4xzLuNCgh1GBU
    FI0NaMhFBJhoNMNgXGOgIed1qCBgrqit+nSOmAAdMd6yTm+0eUJNTPZSYzc1WW1CnqFio4NSvdq2
    Q9uMN0yLR2Re4Rw9drsZo/y26dyfW9nlD3jimpIlctXqddGX0z1vQn1Pol71bRgsUxqZpwkMI0Yb
    jY2MkOBcLSPX7MVaD8ITISNezIbsRNLGeet7yFDECI7tMp7wBu2Ut3w9Q9bZpbIbLyX1ik2UTDfX
    pVf/Zw+jst7tI4NjK5kAGVZcUgB43knjiKVptuawqwnDnK3UYjZNYioDcn8WINUYDDp2MDLeru5H
    hWvSTKYk0J7XaU0v8Zv98tJC/TWBunFguOu+tA7lND2RpTwMZ5I7J4TQZTxFZG54WIFehzUfR5CC
    B8wt8w/8V33yQiaEcanxDbsuOInxGVnGjS+7s4cQP4c7zkDeaOMUmLonTl0q7wJayonHt6sZRXJ/
    VyvNAiaXaliTwPbDGVb+jGYYJe/+9r7CLUwkMU2YI97E8/0J5W/BjdHcm2ddrWXyzgxABnbMydQf
    jzC0ltg6+ILH9p1mHs4q29MjUNDu4EIT7Kx2Bj9D7G7groGE27vQLuYH92W9OM374mnYeaGDrzvf
    gsVJV/x0kZQkiLVgPfVwVOYLVefLD8VwJwrUhcIgJzll9CB7Rx0oz0XERdO9ZbnPwcHqRKMxh4J5
    vuJor4xYMFRovQbIempp77s2794BC/M64dBf7m0xMH1khFmc/XYTpsHGGkcumEOdLxtzfM7ynLcw
    dID0GJsr5/zcfmfARgf5xLHVZgQMS0vduPfly3yXmAiyBicuytXy5FRofdDlwjM5xgyXUh559Kh6
    NjZUsMmsB0m2AbsuA8or/oFyebAzXYZWpIeXi2KDZkIb+VEQGM7Z8LNLhUzMgTE575fIMIXildLl
    cdyrnjza3EA1MRtdw0NuogI9IyY06VZpkH1eaaP/qrfYQFVvU7Auav5sCGZDlu1Sac94IAwMuV6h
    0XrLkVjfrsEMuL8Mnl8HwQRMHSX/rayRnKzPM+bRdjUx4xvnZWISPUb6D4n82K4iKnVg39WhjqgK
    VsGaOR1bmO1CLrsPsUoqSjPYiHyvUPD90eNowFowSglrAqLP2K6KtwVDSt9ZCTFAMBsGCSqGSIb3
    DQEJFDEOHgwAcwBlAHIAdgBlAHIwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTY1NjUzMDkyOTk3MjCC
    A+wGCSqGSIb3DQEHBqCCA90wggPZAgEAMIID0gYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQU
    kvo6/WZNmTzOL9IX5GXNAtp4RNgCAwDDUICCA5gMnl+GMEu7mXmlJ1rpx96yN9WH4jGNoT/a/kOK
    Z84eY8L7+28lRwtt4XMaXoQb8dwntni5Ewz5QKRezl4X0qiCRAjLxxhByma2HcNp00PD2BxHf4x1
    UD+wCxmfIrosrrr19NDA9+Ty/zghA9sMFaBAzf3CaUTY1t4DSYl5BhdxThTby6WSx6v/tijqeMzD
    C67v1h2iewheTLpdUhAzZFDnTMXyRaeFdXea9oNJeOmd64Pnwat9E6dy7obk1yvTi1NuGtkjhBw6
    Z9iQWmfOT9E5jazGYGhG6tDH8ZsRb8bzNkccS5W3ZnNW/5Cg3Xqhkl+Yca4fqvvqwTiIy8TDQqYz
    W8ARoyvNRIameHCg46ZWw7YP0xZCl4ERT4RS70HCsOEIPsrkMA52GYmcUHoYX3pIfA+zICmzRgN1
    8xJWKszWckw2J5JLLDHdgHD8uiUitQ1Z40ddIvVq4tAXTwgr3UtThUq1Yh/XDm02c6QCE6a49y3h
    4mWlHaNzJiFTsTrxqpNyxd/vasy21QkdA/ildhrcMlqWDzYDO+Yh1TyS2rvVNjJ66uUUO4JNgkb8
    Ay9t6omlt9QKrs5Dnv9KTdeSz57ZB/BDoQ4SoBd17cQWlVu+sSUDxdCX0VhnrVf61//sV3GJjCQs
    cxmX80Vog0bxszNGtsrXt6VvyCZBVJVFRV7T3PAyxqhjARrpTO63pJxMGEZ/oW6ZffRpuI9bNcNS
    EntQojeOgtZdKFcdyALJX6X7h8BaDJsW1kykQ7n6ipLK/jDr61KkW1H+41mdR6BX2Cs3xb5hN+xn
    iu/c/4dYxeudzU+Igd+T1NRIk3bLULW71+UMIbyjmnveRQjtliAw7tAZAvi0mraYsM34w+ZAM5qx
    Z//jGnTfA9TzlKnGyUYoKN4uYQUaFiVUVoPuiKQ1ccwTQuylgE64lIhhY/lbIZUk9CU2xzj4htuV
    8crFdCh09VX4RXdqjh1ux+u0how+jTbrITJRsPSG60mNS/VbyYn7Q2OAxT9wc7qILHd8BMWdFqMX
    9gzEq/cUhwDrqOr6PlRO0/D/ToylQX2b3cRpgbs0p9O7g5nNh/cIB1+5MITb2BaUXx4a7hxZdMUx
    C71W4B6JD6zED7PJavsaVWonIMbwGaCf2vXXZC8cJXw2VGGYMWmiK5cHkKWVRedd1dvRpVTOuMWs
    M11rIUTNBK4c5XNtoWvDwvQU/5mdEM1HBqZv/wOoXvhVmxRzwzA+MCEwCQYFKw4DAhoFAAQUSAxp
    8EPbxeUax2m2Bk2QAXpnCVsEFGJ/MAeYCA0KFnlJlXdmiVzgRRxTAgMBhqA=
